const $=s=>document.querySelector(s);
const excelEpoch=Date.UTC(1899,11,30);
let excelFile=null;
const HEADERS=[['A','Inspection_ID'],['B','Inspection_Date'],['C','Week_No'],['D',''],['E','Month'],['F','Package'],['G','Cluster'],['H','Package_Cluster_Check'],['I','Contractor'],['J','Project Director (PD)'],['K','Project Manager (PM)'],['L','Construction Manager (CM)'],['M','HSE Manager (HSEM)'],['N','Section Engineer (SE)'],['O','Your_Name'],['P','Your_Role'],['Q','Area_or_Villa'],['R','Workers_Observed'],['S','Main_High_Risk_Activity'],['T','Stop_Work'],['U','Work_at_Height'],['V','Edge_Protection'],['W','Falling_Object_Prevention'],['X','Excavation_Safety'],['Y','Scaffolding_Compliance'],['Z','PTW_Implementation'],['AA','PTW_Field_Verification'],['AB','MSRA_Quality'],['AC','Lifting/Precast Installation'],['AD','Traffic_Interface'],['AE','Housekeeping/Waste Management'],['AF','Welfare Arrangement'],['AG','Fire_Readiness'],['AH','Supervision_Subcontractor'],['AI','Electrical_Tool_Safety'],['AJ','Total_Score'],['AK','Raw_Score_%'],['AL','Weighted_Score_%'],['AM','Critical_Red_Flag'],['AN','Award_Eligible'],['AO','Rating_Band'],['AP','Repeat_Issue_Seen'],['AQ','Likely_Root_Cause'],['AR','Top_3_Gaps_Observed'],['AS','Immediate_Action_Taken'],['AT','Preventive_Action_Required'],['AU','Positive_Observations'],['AV','Action_Owner'],['AW','Target_Closeout_Date'],['AX','Evidence_Link_or_Photo'],['AY','KPI_for_PD_Attention'],['AZ','KPI_for_PM_Attention'],['BA','KPI_for_CM_Attention'],['BB','KPI_for_HSEM_Followup'],['BC','KPI_for_SE_Supervision'],['BD','Leadership_Visible_Effective'],['BE','Unsafe_Work_Corrected_Immediately'],['BF','Best_Improved_Cluster_this_Week'],['BG','Cluster_Needing_Immediate_Intervention']];
const KPI=[['U','Work_at_Height','Work at Height'],['V','Edge_Protection','Edge Protection'],['W','Falling_Object_Prevention','Falling Object Prevention'],['X','Excavation_Safety','Excavation Safety'],['Y','Scaffolding_Compliance','Scaffolding Compliance'],['Z','PTW_Implementation','PTW Implementation'],['AA','PTW_Field_Verification','PTW Field Verification'],['AB','MSRA_Quality','MSRA Quality'],['AC','Lifting/Precast Installation','Lifting / Precast Installation'],['AD','Traffic_Interface','Traffic Interface'],['AE','Housekeeping/Waste Management','Housekeeping / Waste'],['AF','Welfare Arrangement','Welfare Arrangement'],['AG','Fire_Readiness','Fire Readiness'],['AH','Supervision_Subcontractor','Supervision / Subcontractor'],['AI','Electrical_Tool_Safety','Electrical / Tool Safety']];
const WEIGHTS=[.12,.12,.05,.08,.10,.08,.06,.03,.10,.06,.03,.03,.05,.03,.06];
const CLUSTERS={'Cluster 7A':{pkg:2,contractor:'TAJV'},'Cluster 7B':{pkg:2,contractor:'TAJV'},'Cluster 8A':{pkg:2,contractor:'TAJV'},'Cluster 8B':{pkg:2,contractor:'TAJV'},'Cluster 8C':{pkg:2,contractor:'TAJV'},'Cluster 8D':{pkg:2,contractor:'TAJV'},'Cluster 3':{pkg:3,contractor:'INNOVO'},'Cluster 4':{pkg:3,contractor:'INNOVO'},'Cluster 5':{pkg:3,contractor:'INNOVO'},'Cluster 6':{pkg:3,contractor:'INNOVO'},'Cluster 1A':{pkg:4,contractor:'TAJV'},'Cluster 1B':{pkg:4,contractor:'TAJV'},'Cluster 2A':{pkg:4,contractor:'TAJV'},'Cluster 2B':{pkg:4,contractor:'TAJV'},'Cluster 2C':{pkg:4,contractor:'TAJV'}};
const ALIAS={'Work_at_Height':['work at height','wah','height'], 'Edge_Protection':['edge protection','open edge','edge'], 'Falling_Object_Prevention':['falling object','falling materials','dropped object'], 'Excavation_Safety':['excavation','trench'], 'Scaffolding_Compliance':['scaffold','scaffolding'], 'PTW_Implementation':['ptw implementation','permit implementation','permit to work'], 'PTW_Field_Verification':['field verification','permit verification'], 'MSRA_Quality':['msra','risk assessment','method statement'], 'Lifting/Precast Installation':['lifting','precast','a-frame','a frame'], 'Traffic_Interface':['traffic','man-machine','interface'], 'Housekeeping/Waste Management':['housekeeping','waste','debris'], 'Welfare Arrangement':['welfare'], 'Fire_Readiness':['fire','extinguisher'], 'Supervision_Subcontractor':['supervision','subcontractor'], 'Electrical_Tool_Safety':['electrical','db','cable','tool']};
const mainCols=['B','F','G','I','O','P','Q','R','S','T','AP','AV','AW','AX'];
const textCols=['AQ','AR','AS','AT','AU'];
function esc(s){return String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function unesc(s){return String(s??'').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&amp;/g,'&')}
function id(c){return 'col_'+c}
function setStatus(el,msg,cls=''){el.textContent=msg;el.className='status '+cls}
function serial(iso){if(!iso)return '';const d=new Date(iso+'T00:00:00');return Math.floor((Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())-excelEpoch)/86400000)}
function weekNo(iso){if(!iso)return '';const d=new Date(iso+'T00:00:00');const t=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));const n=t.getUTCDay()||7;t.setUTCDate(t.getUTCDate()+4-n);const y=new Date(Date.UTC(t.getUTCFullYear(),0,1));return Math.ceil((((t-y)/86400000)+1)/7)}
function addDays(iso,n){if(!iso)return '';const d=new Date(iso+'T00:00:00');d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
function norm(s){return String(s||'').toLowerCase().replace(/[^a-z0-9\/\.:\-\s&]/g,' ').replace(/\s+/g,' ').trim()}
function scoreToken(t){let raw=String(t||'').trim().toUpperCase().replace(/,/g,'.');if(!raw||/^(NA|N\/A)$/.test(raw))return '';let s=raw.replace(/[OS]/g,'0').replace(/[IL]/g,'1');if(/^[0-5](\.0|\.5)?$/.test(s))return String(Number(s));const m=s.match(/^([0-5])([05])$/);return m?`${m[1]}.${m[2]}`:''}
function scoreLine(line){const tokens=String(line||'').match(/[0-5](?:[\.,][05])?|[0-5][05]|N\/?A|NA/gi)||[];for(let i=tokens.length-1;i>=0;i--){const v=scoreToken(tokens[i]);if(v)return v}return ''}
function extractDate(t){const m=[...String(t).matchAll(/(\d{1,2})[\/\-.](\d{1,2})[\/\-.](20\d{2})/g)][0];return m?`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`:''}
function extractCluster(t){const n=norm(t);let cluster='',pkg='';for(const code of ['1A','1B','2A','2B','2C','7A','7B','8A','8B','8C','8D']){if(new RegExp(`\\bcluster\\s*${code.toLowerCase()}\\b`).test(n)||new RegExp(`\\b${code.toLowerCase()}\\b`).test(n)){cluster=`Cluster ${code}`;break}}const simple=n.match(/cluster\s*[:\-]?\s*([3456])\b/);if(!cluster&&simple)cluster=`Cluster ${simple[1]}`;const p=n.match(/package\s*[:\-]?\s*([234])\b/);if(p)pkg=p[1];if(!pkg&&cluster&&CLUSTERS[cluster])pkg=String(CLUSTERS[cluster].pkg);return{cluster,pkg}}
function extractScores(text){const lines=String(text).split(/\n+/).map(x=>x.trim()).filter(Boolean),out={};for(const [k,a] of Object.entries(ALIAS)){for(let i=0;i<lines.length;i++){const l=lines[i].toLowerCase();if(a.some(x=>l.includes(x))){const v=scoreLine(lines[i])||scoreLine(lines[i+1]||'');if(v){out[k]=v;break}}}}return out}
function field(col){return document.getElementById(id(col))}
function get(col){return field(col)?.value?.trim()||''}
function put(col,val){const e=field(col);if(e)e.value=val??''}
function num(v){const n=Number(v);return Number.isFinite(n)?n:null}
function scores(){return Object.fromEntries(KPI.map(([c,k])=>[k,get(c)]))}
function lowest(){return KPI.map(([c,k,l])=>({col:c,key:k,label:l,v:num(get(c))})).filter(x=>x.v!==null).sort((a,b)=>a.v-b.v).slice(0,3)}
function updateDerived(){const d=get('B');if(d){put('C',weekNo(d));put('E',d.slice(0,7));put('AW',get('AW')||addDays(d,7))}const cl=get('G');if(CLUSTERS[cl]){put('F',String(CLUSTERS[cl].pkg));put('I',CLUSTERS[cl].contractor)}const vals=KPI.map(([c])=>num(get(c))).filter(v=>v!==null);const total=vals.reduce((a,b)=>a+b,0);const count=vals.length;let weighted=0;KPI.forEach(([c],i)=>{const v=num(get(c));if(v!==null)weighted+=v*WEIGHTS[i]});const raw=count?total/75:'';const wp=count?weighted/5:'';const critical=['U','X','Y','Z','AC'].some(c=>num(get(c))!==null&&num(get(c))<=1);let band='';if(count){band=wp<.4?'Critical':wp<.6?'Poor':wp<.75?'Needs Improvement':wp<.9?'Good':'Excellent'}put('AJ',count?String(total):'');put('AK',count?String(raw):'');put('AL',count?String(wp):'');put('AM',count?(critical?'YES':'NO'):'');put('AN',count?(!critical&&wp>=.9?'YES':'NO'):'');put('AO',band);const lows=lowest();if(!get('S'))put('S',lows[0]?.label||'');if(!get('AQ'))put('AQ',lows.length?'Poor supervision / weak implementation of low scoring KPI controls.':'');if(!get('AR'))put('AR',lows.map((x,i)=>`${i+1}. ${x.label} scored ${x.v}/5 and requires management action.`).join('\n'));if(!get('AS'))put('AS',lows.map(x=>`${x.label}: stop/hold affected activity where required and rectify immediate unsafe condition.`).join('\n'));if(!get('AT'))put('AT',lows.map(x=>`${x.label}: implement corrective action, close supervision and closeout evidence.`).join('\n'));put('AY',lows[0]?.label||'');put('AZ',lows[1]?.label||'');put('BA',lows[2]?.label||'');put('BB',lows.map(x=>x.label).join(', '));put('BC',lows.map(x=>x.label).join(', '));put('BD',critical?'NO':'YES');put('BE',get('T')==='YES'?'YES':'');put('BF',band==='Good'||band==='Excellent'?get('G'):'');put('BG',critical?get('G'):'');$('#summary').innerHTML=count?`Scores entered: ${count}/15 | Total: ${total}/75 | Raw: ${(Number(raw)*100).toFixed(1)}% | Weighted: ${(Number(wp)*100).toFixed(1)}% | Critical Red Flag: ${critical?'YES':'NO'} | Band: ${band}`:'No scores yet.'}
function makeField(col,area){const name=HEADERS.find(x=>x[0]===col)?.[1]||col;const type=['B','AW'].includes(col)?'date':'text';const tag=textCols.includes(col)?`<textarea id="${id(col)}" rows="3"></textarea>`:`<input id="${id(col)}" type="${type}">`;area.insertAdjacentHTML('beforeend',`<div class="field ${textCols.includes(col)?'full':''}"><label>${col} - ${name}</label>${tag}</div>`)}
function initUI(){mainCols.forEach(c=>makeField(c,$('#mainFields')));textCols.forEach(c=>makeField(c,$('#textFields')));KPI.forEach(([c,k,l],i)=>{$('#kpiGrid').insertAdjacentHTML('beforeend',`<div class="kpi-card"><label>${i+1}. ${c} - ${l}</label><input class="score" id="${id(c)}" inputmode="decimal"></div>`)});HEADERS.forEach(([c,h])=>{$('#allColumns').insertAdjacentHTML('beforeend',`<div class="col-field"><div class="col-code">${c}</div><input id="full_${c}" placeholder="${h}"></div>`)});HEADERS.forEach(([c])=>{const e=field(c);if(e)e.addEventListener('input',()=>{syncFull();updateDerived();syncFull()})});document.querySelectorAll('.score').forEach(e=>e.addEventListener('input',()=>{updateDerived();syncFull()}));document.querySelectorAll('[id^=full_]').forEach(e=>e.addEventListener('input',()=>{const c=e.id.replace('full_','');if(field(c))field(c).value=e.value;updateDerived()}));put('O','Javed Iqbal');put('P','KEO');put('T','YES');put('AP','YES');put('AV','Project Manager and Construction Manager');put('AX','Site photo / closeout evidence to be attached');syncFull()}
function syncFull(){HEADERS.forEach(([c])=>{const e=document.getElementById('full_'+c);if(e)e.value=get(c)})}
async function readImage(){const f=$('#imageInput').files?.[0];if(!f){setStatus($('#ocrStatus'),'Choose photo first','error');return}setStatus($('#ocrStatus'),'Reading photo...');try{const r=await Tesseract.recognize(f,'eng',{logger:m=>{if(m.status==='recognizing text')setStatus($('#ocrStatus'),`OCR ${Math.round(m.progress*100)}%`)}});const t=r.data.text||'';$('#ocrText').value=t;const d=extractDate(t);if(d)put('B',d);const cp=extractCluster(t);if(cp.cluster)put('G',cp.cluster);if(cp.pkg)put('F',cp.pkg);if(cp.cluster&&CLUSTERS[cp.cluster])put('I',CLUSTERS[cp.cluster].contractor);const m=String(t).match(/\b(?:villa|vila|vl)\s*[:\-]?\s*(\d{1,4}[A-Z]?)\b/i);if(m)put('Q',`Villa ${m[1]}`);const sc=extractScores(t);KPI.forEach(([c,k])=>{if(sc[k])put(c,sc[k])});updateDerived();syncFull();setStatus($('#ocrStatus'),'Photo read completed. Review empty fields manually.','ok')}catch(e){setStatus($('#ocrStatus'),'OCR failed: '+e.message,'error')}}
async function loadZip(){if(excelFile)return await JSZip.loadAsync(await excelFile.arrayBuffer());const b=await fetch('original.xlsx');if(!b.ok)throw new Error('original.xlsx not found');return await JSZip.loadAsync(await b.arrayBuffer())}
async function txt(zip,p){const f=zip.file(p);if(!f)throw new Error(p+' missing');return await f.async('text')}
function weeklyPath(workbook,rels){const m=workbook.match(/<sheet[^>]*name="Weekly_Inspections"[^>]*r:id="([^"]+)"/);if(!m)throw new Error('Weekly_Inspections sheet not found');const r=new RegExp(`<Relationship[^>]*Id="${m[1]}"[^>]*Target="([^"]+)"`);const rm=rels.match(r);if(!rm)throw new Error('Weekly_Inspections relationship not found');return 'xl/'+rm[1].replace(/^\.\.\//,'')}
function rows(xml){return [...xml.matchAll(/<row r="(\d+)"[^>]*>.*?<\/row>/gs)].map(m=>({r:Number(m[1]),xml:m[0],start:m.index,end:m.index+m[0].length}))}
function cell(row,col){const re=new RegExp(`<c r="${col}${row.r}"[^>]*(?:>.*?<\\/c>|\\/>)`,'s');const m=row.xml.match(re);return m?m[0]:''}
function hasVal(row,col){const c=cell(row,col);return /<v>[^<]*<\/v>/.test(c)&&!/<v\s*\/>/.test(c)&&!/<v><\/v>/.test(c)}
function firstEmpty(rows){for(const row of rows){if(row.r>=4&&!hasVal(row,'B'))return row}throw new Error('No empty pre-formatted row found in original file. Add blank formatted rows in Weekly_Inspections.')}
function appendShared(files,s){let xml=files.shared;const idx=(xml.match(/<si>/g)||[]).length;xml=xml.replace(/<\/sst>/,`<si><t>${esc(s)}</t></si></sst>`);xml=xml.replace(/count="\d+"/,m=>`count="${Number(m.match(/\d+/)[0])+1}"`);xml=xml.replace(/uniqueCount="\d+"/,m=>`uniqueCount="${Number(m.match(/\d+/)[0])+1}"`);files.shared=xml;return idx}
function putV(cxml,val){if(/<v[\s\/]/.test(cxml)){return cxml.replace(/<v(?:[^>]*)>.*?<\/v>|<v\s*\/>/s,`<v>${esc(val)}</v>`)}return cxml.replace(/<\/c>$/,`<v>${esc(val)}</v></c>`).replace(/\/>$/,`><v>${esc(val)}</v></c>`)}
function setCell(row,col,value,type,files){if(value===''||value===null||value===undefined)return;const old=cell(row,col);if(!old)return;let nv=value;if(type==='s'&&!/<f[\s>]/.test(old)){nv=appendShared(files,String(value));let open=old.match(/^<c\s+([^>]*)/)[1];open=open.replace(/\s+t="[^"]*"/g,'')+' t="s"';let neu=old.replace(/^<c\s+[^>]*/,`<c ${open}`);neu=putV(neu,nv);row.xml=row.xml.replace(old,neu);return}let neu=old;if(type==='n'&&!/<f[\s>]/.test(old)){neu=neu.replace(/\s+t="[^"]*"/,'')}if(type==='s'&&/<f[\s>]/.test(old)){if(!/\s+t="str"/.test(neu)&&!/\s+t="s"/.test(neu))neu=neu.replace(/^<c /,'<c t="str" ')}neu=putV(neu,nv);row.xml=row.xml.replace(old,neu)}
function allData(){updateDerived();syncFull();const out=[];const dateCols=new Set(['B','AW']);const numCols=new Set(['C','F','R','U','V','W','X','Y','Z','AA','AB','AC','AD','AE','AF','AG','AH','AI','AJ','AK','AL']);HEADERS.forEach(([c])=>{let v=get(c)||document.getElementById('full_'+c)?.value?.trim()||'';if(!v)return;if(dateCols.has(c))out.push([c,serial(v),'n']);else if(numCols.has(c))out.push([c,v,'n']);else out.push([c,v,'s'])});return out}
function forceRecalc(workbook){if(/<calcPr[^>]*\/>/.test(workbook))return workbook.replace(/<calcPr[^>]*\/>/,'<calcPr calcMode="auto" fullCalcOnLoad="1" forceFullCalc="1"/>');if(/<calcPr[^>]*>.*?<\/calcPr>/s.test(workbook))return workbook.replace(/<calcPr[^>]*>.*?<\/calcPr>/s,'<calcPr calcMode="auto" fullCalcOnLoad="1" forceFullCalc="1"/>');return workbook.replace(/<\/workbook>/,'<calcPr calcMode="auto" fullCalcOnLoad="1" forceFullCalc="1"/></workbook>')}
async function updateExcel(){try{setStatus($('#status'),'Opening original file and preserving exact row/cell design...');const zip=await loadZip();let workbook=await txt(zip,'xl/workbook.xml');const rels=await txt(zip,'xl/_rels/workbook.xml.rels');const path=weeklyPath(workbook,rels);let sheet=await txt(zip,path);let shared=await txt(zip,'xl/sharedStrings.xml');const files={shared};const allRows=rows(sheet);const row=firstEmpty(allRows);const original=row.xml;allData().forEach(([c,v,t])=>setCell(row,c,v,t,files));sheet=sheet.slice(0,row.start)+row.xml+sheet.slice(row.end);workbook=forceRecalc(workbook);zip.file(path,sheet);zip.file('xl/sharedStrings.xml',files.shared);zip.file('xl/workbook.xml',workbook);if(zip.file('xl/calcChain.xml'))zip.remove('xl/calcChain.xml');const blob=await zip.generateAsync({type:'blob',compression:'DEFLATE'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`ALDAR_ORIGINAL_EXACT_UPDATED_ROW_${row.r}.xlsx`;a.click();setStatus($('#status'),`Done. Row ${row.r} updated inside original workbook. Cell formats, fonts, colors, alignment, formulas and sheet design preserved.`,'ok')}catch(e){console.error(e);setStatus($('#status'),'Failed: '+e.message,'error')}}
document.addEventListener('DOMContentLoaded',()=>{initUI();$('#imageInput').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=ev=>{$('#preview').src=ev.target.result;$('#preview').style.display='block';$('#ph').style.display='none';setTimeout(readImage,200)};r.readAsDataURL(f)};$('#excelInput').onchange=e=>{excelFile=e.target.files?.[0]||null;setStatus($('#excelStatus'),excelFile?`Selected: ${excelFile.name}`:'Included original.xlsx ready.',excelFile?'ok':'')};$('#readBtn').onclick=readImage;$('#updateBtn').onclick=updateExcel});
