const $=s=>document.querySelector(s);
const CLUSTERS={"Cluster 7A":{"pkg":2,"contractor":"TAJV","pd":"Hicham Adel Narch","pm":"Ghaidh Alfaour","cm":"George Deeb","hsem":"Timur","se":"Liqat"},"Cluster 7B":{"pkg":2,"contractor":"TAJV","pd":"Hicham Adel Narch","pm":"Ghaidh Alfaour","cm":"George Deeb","hsem":"Timur","se":"Eyad"},"Cluster 8A":{"pkg":2,"contractor":"TAJV","pd":"Hicham Adel Narch","pm":"Ghaidh Alfaour","cm":"Mohamed Salama","hsem":"Timur","se":"Ahmad Adel"},"Cluster 8B":{"pkg":2,"contractor":"TAJV","pd":"Hicham Adel Narch","pm":"Ghaidh Alfaour","cm":"Mohamed Salama","hsem":"Timur","se":"Ahmad Adel"},"Cluster 8C":{"pkg":2,"contractor":"TAJV","pd":"Hicham Adel Narch","pm":"Ghaidh Alfaour","cm":"George Deeb","hsem":"Timur","se":"Ahmad Adel"},"Cluster 8D":{"pkg":2,"contractor":"TAJV","pd":"Hicham Adel Narch","pm":"Ghaidh Alfaour","cm":"George Deeb","hsem":"Timur","se":"Ahmad Adel"},"Cluster 3":{"pkg":3,"contractor":"INNOVO","pd":"Kahtan Tikriti","pm":"Aiman Abdullah","cm":"Salama Al Samdy","hsem":"Mazen Al Atwani","se":"0"},"Cluster 4":{"pkg":3,"contractor":"INNOVO","pd":"Kahtan Tikriti","pm":"Aiman Abdullah","cm":"Baha Basheer","hsem":"Mazen Al Atwani","se":"0"},"Cluster 5":{"pkg":3,"contractor":"INNOVO","pd":"Kahtan Tikriti","pm":"Michael Ghali","cm":"Robair Louies","hsem":"Mazen Al Atwani","se":"0"},"Cluster 6":{"pkg":3,"contractor":"INNOVO","pd":"Kahtan Tikriti","pm":"Michael Ghali","cm":"Remon Karas","hsem":"Mazen Al Atwani","se":"0"},"Cluster 1A":{"pkg":4,"contractor":"TAJV","pd":"Hicham Adel Narch","pm":"Ghaidh Alfaour","cm":"Alaa Hegab","hsem":"Timur Terakopov","se":"Amr Taha"},"Cluster 1B":{"pkg":4,"contractor":"TAJV","pd":"Hicham Adel Narch","pm":"Ghaidh Alfaour","cm":"Hossam Ali Maher","hsem":"Timur Terakopov","se":"Md Ramadan / Osama Said"},"Cluster 2A":{"pkg":4,"contractor":"TAJV","pd":"Hicham Adel Narch","pm":"Ghaidh Alfaour","cm":"Ahmed Salah Hassan Dewidar","hsem":"Timur Terakopov","se":"Rami Issa"},"Cluster 2B":{"pkg":4,"contractor":"TAJV","pd":"Hicham Adel Narch","pm":"Ghaidh Alfaour","cm":"Ahmed Salah Hassan Dewidar","hsem":"Timur Terakopov","se":"Rami Issa"},"Cluster 2C":{"pkg":4,"contractor":"TAJV","pd":"Hicham Adel Narch","pm":"Ghaidh Alfaour","cm":"Ahmed Salah Hassan Dewidar","hsem":"Timur Terakopov","se":"Salah Nayef"}};
const KPI=[["U","Work_at_Height","Work at Height Control"],["V","Edge_Protection","Edge Protection"],["W","Falling_Object_Prevention","Falling Object Prevention"],["X","Excavation_Safety","Excavation Safety"],["Y","Scaffolding_Compliance","Scaffolding Compliance"],["Z","PTW_Implementation","PTW Implementation"],["AA","PTW_Field_Verification","PTW Field Verification"],["AB","MSRA_Quality","MSRA Quality"],["AC","Lifting/Precast Installation","Lifting/Precast Installation"],["AD","Traffic_Interface","Traffic & Man-Machine Interface"],["AE","Housekeeping/Waste Management","Housekeeping/Waste Management"],["AF","Welfare Arrangement","Welfare Arrangement"],["AG","Fire_Readiness","Fire Readiness"],["AH","Supervision_Subcontractor","Supervision & Subcontractor Control"],["AI","Electrical_Tool_Safety","Temporary Electrical & Tool Safety"]];
const ALIAS={"Work_at_Height":["work at height","wah"],"Edge_Protection":["edge protection","open edge"],"Falling_Object_Prevention":["falling object","falling materials"],"Excavation_Safety":["excavation","trench"],"Scaffolding_Compliance":["scaffold","scaffolding"],"PTW_Implementation":["ptw implementation","permit implementation","work permit"],"PTW_Field_Verification":["field verification","permit verification"],"MSRA_Quality":["msra","risk assessment"],"Lifting/Precast Installation":["lifting","precast","a-frame","a frame"],"Traffic_Interface":["traffic","man-machine"],"Housekeeping/Waste Management":["housekeeping","waste","debris"],"Welfare Arrangement":["welfare"],"Fire_Readiness":["fire","extinguisher"],"Supervision_Subcontractor":["supervision","subcontractor"],"Electrical_Tool_Safety":["electrical","db","cable"]};
let excelFile=null; const excelEpoch=Date.UTC(1899,11,30);
function setStatus(s,t=""){const e=$("#status");e.textContent=s;e.style.background=t==="error"?"#fff3f3":t==="success"?"#f3fff7":"#fff"}
function setOcr(s,t=""){const e=$("#ocrStatus");e.textContent=s;e.style.background=t==="error"?"#fff3f3":t==="success"?"#f3fff7":"#fff"}
function setExcel(s,t=""){const e=$("#excelStatus");e.textContent=s;e.style.background=t==="error"?"#fff3f3":t==="success"?"#f3fff7":"#fff"}
function esc(s){return String(s??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
function unesc(s){return String(s??"").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&amp;/g,"&")}
function colNum(col){let n=0;for(const ch of col)n=n*26+ch.charCodeAt(0)-64;return n}
function serial(iso){if(!iso)return"";const d=new Date(iso+"T00:00:00");return Math.floor((Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())-excelEpoch)/86400000)}
function weekNo(iso){if(!iso)return"";const d=new Date(iso+"T00:00:00");const t=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));const n=t.getUTCDay()||7;t.setUTCDate(t.getUTCDate()+4-n);const y=new Date(Date.UTC(t.getUTCFullYear(),0,1));return Math.ceil((((t-y)/86400000)+1)/7)}
function addDays(iso,days){if(!iso)return"";const d=new Date(iso+"T00:00:00");d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}
function norm(s){return String(s||"").toLowerCase().replace(/[^a-z0-9\/.:\-\s&]/g," ").replace(/\s+/g," ").trim()}
function monthNo(m){const a={jan:1,january:1,feb:2,february:2,mar:3,march:3,apr:4,april:4,may:5,jun:6,june:6,jul:7,july:7,aug:8,august:8,sep:9,sept:9,september:9,oct:10,october:10,nov:11,november:11,dec:12,december:12};return a[String(m||"").toLowerCase()]||""}
function extractDate(t){const s=String(t||"");let m=[...s.matchAll(/(\d{1,2})[\/\-.](\d{1,2})[\/\-.](20\d{2})/g)][0];if(m)return m[3]+"-"+m[2].padStart(2,"0")+"-"+m[1].padStart(2,"0");m=s.match(/(\d{1,2})\s*[\-\/\.\s]\s*(Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:t|tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)\s*[\-\/\.\s]\s*(20\d{2})/i);if(m){const mo=String(monthNo(m[2])).padStart(2,"0");return m[3]+"-"+mo+"-"+m[1].padStart(2,"0")}m=s.match(/(20\d{2})[\/\-.](\d{1,2})[\/\-.](\d{1,2})/);return m?m[1]+"-"+m[2].padStart(2,"0")+"-"+m[3].padStart(2,"0"):""}
function extractCluster(t){const n=norm(t).replace(/clustar|clusfer|clustcr|claster/g,"cluster").replace(/packagc|packaqe|pkg|pckg/g,"package");let cluster="",pkg="";for(const code of ["1A","1B","2A","2B","2C","7A","7B","8A","8B","8C","8D"]){const c=code.toLowerCase().replace(/([0-9])([a-z])/,'$1\\s*$2');if(new RegExp('\\b(?:cluster|cl|c)\\s*[:\\-]?\\s*'+c+'\\b').test(n)||new RegExp('\\b'+c+'\\b').test(n)){cluster="Cluster "+code;break}}const simple=n.match(/(?:cluster|cl|c)\s*[:\-]?\s*([3456])\b/);if(!cluster&&simple)cluster="Cluster "+simple[1];const p=n.match(/(?:package|pack)\s*[:\-]?\s*([234])\b/);if(p)pkg=p[1];if(!pkg&&cluster&&CLUSTERS[cluster])pkg=String(CLUSTERS[cluster].pkg);return{cluster,pkg}}
function extractContractor(t,cluster,pkg){const n=norm(t);if(/innovo|inovo|invovo/.test(n))return"INNOVO";if(/tajv|ta jv|joint venture|t a j v/.test(n))return"TAJV";if(cluster&&CLUSTERS[cluster])return CLUSTERS[cluster].contractor;if(String(pkg)==="3")return"INNOVO";if(["2","4"].includes(String(pkg)))return"TAJV";return""}
function cleanOcrLine(l){return norm(l).replace(/work al height|work at heiqht|w0rk at height/g,"work at height").replace(/edqe|edgc/g,"edge").replace(/scaf folding|scaffald/g,"scaffolding").replace(/excavalion|excavatlon/g,"excavation").replace(/electrica1|electrlcal/g,"electrical").replace(/house keeping/g,"housekeeping")}
function scoreToken(t){let raw=String(t||"").trim().toUpperCase().replace(/,/g,".");if(!raw)return"";if(/^(NA|N\/A|N-A)$/.test(raw))return"";let x=raw.replace(/[OSQ]/g,"0").replace(/[IL|]/g,"1").replace(/[B]/g,"8");let m=x.match(/^([0-5])(?:\.([05]))?$/);if(m)return m[2]?`${m[1]}.${m[2]}`:String(Number(m[1]));m=x.match(/^([0-5])([05])$/);if(m)return `${m[1]}.${m[2]}`;m=x.match(/(?:score|kpi|rating)?\s*[:=\-]?\s*([0-5])(?:\.([05]))?\s*(?:\/\s*5)?/i);if(m)return m[2]?`${m[1]}.${m[2]}`:String(Number(m[1]));return""}
function scoreLine(line){const s=String(line||"");const tokens=s.match(/(?:score|kpi|rating)?\s*[:=\-]?\s*[0-5](?:[\.,][05])?\s*(?:\/\s*5)?|[0-5][05]|N\/?A|NA/gi)||[];for(let i=tokens.length-1;i>=0;i--){const v=scoreToken(tokens[i]);if(v)return v}return""}
function lineHasAlias(line,aliases){const l=cleanOcrLine(line);return aliases.some(a=>{const x=norm(a);if(l.includes(x))return true;const words=x.split(/\s|\//).filter(w=>w.length>2);return words.length&&words.every(w=>l.includes(w.slice(0,Math.min(w.length,6))))})}
function extractScores(text){const lines=String(text).split(/\n+/).map(x=>x.trim()).filter(Boolean),out={};for(const [k,a] of Object.entries(ALIAS)){for(let i=0;i<lines.length;i++){if(lineHasAlias(lines[i],a)){let v=scoreLine(lines[i])||scoreLine(lines[i+1]||"")||scoreLine(lines[i+2]||"");if(v){out[k]=v;break}}}}const orderedNums=[];for(const line of lines){const l=cleanOcrLine(line);if(/score|kpi|control|safety|compliance|implementation|readiness|arrangement|interface|quality|management|supervision|electrical|housekeeping|welfare|fire|ptw|msra|lifting|traffic|scaffold|excavation|edge|height/.test(l)){const v=scoreLine(line);if(v)orderedNums.push(v)}}if(Object.keys(out).length<10&&orderedNums.length>=10){let idx=0;for(const k of KPI.map(x=>x[1])){if(!out[k]&&orderedNums[idx])out[k]=orderedNums[idx];idx++}}
if(Object.keys(out).length<10){
  for(const line of lines){
    const nums=(String(line).match(/\b[0-5](?:[\.,][05])?\b/g)||[]).map(scoreToken).filter(Boolean);
    if(nums.length>=10){let idx=0;for(const k of KPI.map(x=>x[1])){if(!out[k]&&nums[idx])out[k]=nums[idx];idx++}break}
  }
}
return out}
function extractArea(t){const s=String(t||"");let m=s.match(/\b(?:villa|vila|vl|unit|plot|area)\s*[:\-]?\s*([A-Z]?\d{1,5}[A-Z]?|\d+[A-Z])/i);if(m)return /area/i.test(m[0])?m[1]:"Villa "+m[1];m=s.match(/\b(?:road|sector|zone|street)\s*[:\-]?\s*([A-Z0-9\-\/ ]{2,20})/i);return m?m[0].trim():""}
function extractStopWork(t){const n=norm(t);if(/stop\s*work.*\bno\b|no\s*stop\s*work/.test(n))return"NO";if(/stop\s*work|work\s*stoppage|activity\s*stopped/.test(n))return"YES";return""}
function extractActivity(t){const lines=String(t||"").split(/\n+/).map(x=>x.trim()).filter(Boolean);for(const [key,aliases] of Object.entries(ALIAS)){if(lines.some(line=>lineHasAlias(line,aliases)))return KPI.find(k=>k[1]===key)?.[2]||key}return""}
function renderKpis(){const g=$("#kpiGrid");g.innerHTML=KPI.map((k,i)=>`<div class="kpi-card"><h3>${i+1}. ${k[2]}</h3><input class="score-input" data-key="${k[1]}"></div>`).join("");document.querySelectorAll(".score-input").forEach(x=>{x.oninput=()=>calc(true);x.onchange=()=>calc(true)})}
function scores(){const o={};document.querySelectorAll(".score-input").forEach(x=>o[x.dataset.key]=x.value.trim());return o}
function val(v){const n=Number(v);return Number.isFinite(n)?n:null}
function low(){return KPI.map(k=>({key:k[1],label:k[2],v:val(scores()[k[1]])})).filter(x=>x.v!==null).sort((a,b)=>a.v-b.v).slice(0,3)}
function calc(force=false){const s=scores();let total=0,count=0;KPI.forEach(k=>{const n=val(s[k[1]]);if(n!==null){total+=n;count++}});const raw=count?total/75:"";let weighted=0;if(count){const w=[.12,.12,.05,.08,.10,.08,.06,.03,.10,.06,.03,.03,.05,.03,.06];KPI.forEach((k,i)=>{const n=val(s[k[1]]);if(n!==null)weighted+=n*w[i]});weighted=weighted/5}const crit=["Work_at_Height","Excavation_Safety","Scaffolding_Compliance","PTW_Implementation","Lifting/Precast Installation"].some(k=>val(s[k])!==null&&val(s[k])<=1);let band=count?(weighted<.4?"Critical":weighted<.6?"Poor":weighted<.75?"Needs Improvement":weighted<.9?"Good":"Excellent"):"";$("#ratingBand").value=band;const lows=low();if(force||!$("#mainActivity").value)$("#mainActivity").value=lows[0]?.label||"";if(force||!$("#rootCause").value)$("#rootCause").value=lows.length?"Poor supervision / weak implementation of low scoring KPI controls.":"";if(force||!$("#topGaps").value)$("#topGaps").value=lows.map((x,i)=>`${i+1}. ${x.label} scored ${x.v}/5 and requires management action.`).join("\n");if(force||!$("#immediateAction").value)$("#immediateAction").value=lows.map(x=>`${x.label}: stop/hold affected activity where required and rectify immediate unsafe condition.`).join("\n");if(force||!$("#preventiveAction").value)$("#preventiveAction").value=lows.map(x=>`${x.label}: Project Manager and Construction Manager shall implement corrective action, supervision and closeout evidence.`).join("\n");$("#summary").innerHTML=count?`Scores: ${count}/15 | Total: ${total} | Raw: ${(raw*100).toFixed(1)}% | Weighted: ${(weighted*100).toFixed(1)}% | Critical: ${crit?"YES":"NO"} | Band: ${band}`:"No scores yet."}
async function readImage(){const f=$("#imageInput").files?.[0];if(!f){setOcr("Choose photo first","error");return}setOcr("Reading photo...");try{const r=await Tesseract.recognize(f,"eng",{logger:m=>{if(m.status==="recognizing text")setOcr(`OCR ${Math.round(m.progress*100)}%`)}});const t=r.data.text||"";$("#ocrText").value=t;const d=extractDate(t);if(d)$("#inspectionDate").value=d;const cp=extractCluster(t);if(cp.cluster)$("#cluster").value=cp.cluster;if(cp.pkg)$("#package").value=cp.pkg;const con=extractContractor(t,cp.cluster,cp.pkg);if(con)$("#contractor").value=con;const ar=extractArea(t);if(ar)$("#areaText").value=ar;const sw=extractStopWork(t);if(sw)$("#stopWork").value=sw;const act=extractActivity(t);if(act)$("#mainActivity").value=act;const sc=extractScores(t);document.querySelectorAll(".score-input").forEach(x=>x.value=sc[x.dataset.key]||"");updateDerived();calc(true);setOcr("Photo read completed. Auto-filled "+Object.keys(sc).length+" KPI value(s). Blank KPI cells are ready for manual entry.","success")}catch(e){setOcr("OCR failed: "+e.message,"error")}}
function updateDerived(){const d=$("#inspectionDate").value;$("#weekNo").value=weekNo(d);if(d)$("#targetCloseoutDate").value=addDays(d,7);const cl=$("#cluster").value.trim();if(CLUSTERS[cl]){$("#package").value=String(CLUSTERS[cl].pkg);$("#contractor").value=CLUSTERS[cl].contractor}}
async function loadZip(){if(excelFile)return await JSZip.loadAsync(await excelFile.arrayBuffer());const b=await fetch("original.xlsx");if(!b.ok)throw new Error("original.xlsx not found");return await JSZip.loadAsync(await b.arrayBuffer())}
async function getText(zip,p){const f=zip.file(p);if(!f)throw new Error(p+" missing");return await f.async("text")}
function findWeeklySheetPath(workbook, rels){const sheetTags=[...workbook.matchAll(/<sheet[^>]*name="Weekly_Inspections"[^>]*r:id="([^"]+)"/g)];if(!sheetTags.length)throw new Error("Weekly_Inspections sheet not found");const rid=sheetTags[0][1];const rel=[...rels.matchAll(/<Relationship[^>]*Id="([^"]+)"[^>]*Target="([^"]+)"/g)].find(x=>x[1]===rid);if(!rel)throw new Error("Weekly relationship not found");return "xl/"+rel[2].replace(/^\.\.\//,"")}
function getRows(xml){return [...xml.matchAll(/<row r="(\d+)"[^>]*>.*?<\/row>/gs)].map(m=>({r:Number(m[1]),xml:m[0],start:m.index,end:m.index+m[0].length}))}
function cellIn(row,col){const r=row.r;const re=new RegExp(`<c r="${col}${r}"[^>]*>.*?<\\/c>`,"s");const m=row.xml.match(re);return m?m[0]:""}
function hasValue(row,col){const c=cellIn(row,col);return /<v>[^<]+<\/v>/.test(c)}
function firstEmptyDataRow(rows){for(const row of rows){if(row.r>=4&&!hasValue(row,"B"))return row}throw new Error("No empty pre-formatted row found. Add more blank rows in original template.")}
function appendSharedString(files,s){let xml=files.shared;const countMatch=xml.match(/count="(\d+)"/);const uniqueMatch=xml.match(/uniqueCount="(\d+)"/);const idx=(xml.match(/<si>/g)||[]).length;xml=xml.replace(/<\/sst>/,`<si><t>${esc(s)}</t></si></sst>`);if(countMatch)xml=xml.replace(/count="\d+"/,`count="${Number(countMatch[1])+1}"`);if(uniqueMatch)xml=xml.replace(/uniqueCount="\d+"/,`uniqueCount="${Number(uniqueMatch[1])+1}"`);files.shared=xml;return idx}

function setCell(row,col,value,type,files){if(value===""||value===null||value===undefined)return;const r=row.r;const ref=col+r;let v=value;let attrs="";const old=cellIn(row,col);const baseStyle=cellStyleId(old)||files.templateStyles[col]||0;const sid=ensureCenterWrapBlueStyle(files,baseStyle);const sAttr=' s="'+sid+'"';if(type==="s"){v=appendSharedString(files,String(value));attrs=' t="s"'}else{v=String(value)}let newCell='<c r="'+ref+'"'+sAttr+attrs+'><v>'+esc(v)+'</v></c>';if(old){row.xml=row.xml.replace(old,newCell)}else{const cells=[...row.xml.matchAll(new RegExp('<c r="([A-Z]+)'+r+'"[^>]*>.*?<\\/c>','gs'))];let inserted=false;for(const c of cells){if(colNum(c[1])>colNum(col)){row.xml=row.xml.replace(c[0],newCell+c[0]);inserted=true;break}}if(!inserted)row.xml=row.xml.replace(/<\/row>/,newCell+"</row>")}}
function scoreStats(){const s=scores();let total=0,count=0;KPI.forEach(k=>{const n=val(s[k[1]]);if(n!==null){total+=n;count++}});const w=[.12,.12,.05,.08,.10,.08,.06,.03,.10,.06,.03,.03,.05,.03,.06];let weighted=0;KPI.forEach((k,i)=>{const n=val(s[k[1]]);if(n!==null)weighted+=n*w[i]});weighted=weighted/5;const raw=total/75;const red=["Work_at_Height","Excavation_Safety","Scaffolding_Compliance","PTW_Implementation","Lifting/Precast Installation"].some(k=>val(s[k])!==null&&val(s[k])<=1);const band=count?(weighted<.4?"Critical":weighted<.6?"Poor":weighted<.75?"Needs Improvement":weighted<.9?"Good":"Excellent"):"";return{total,count,raw,weighted,red,band}}
function yyyymm(iso){return iso?iso.slice(0,7):""}
function serialText(iso){return iso?serial(iso):""}
function genInspectionId(){const manual=$("#inspectionId")?$("#inspectionId").value.trim():"";if(manual)return manual;const d=$("#inspectionDate").value.replaceAll("-","");const cl=$("#cluster").value.replace(/[^0-9A-Z]/gi,"");return d&&cl?`SIDP3-BW-KEO-ZZ-ZZ-XX-RP-HS-${d}-${cl}`:""}
function dataMap(){calc(true);const d=$("#inspectionDate").value,cl=$("#cluster").value.trim(),pkg=$("#package").value.trim(),sc=scores(),st=scoreStats();const info=CLUSTERS[cl]||{};const lows=low().map(x=>x.label).join(", ");return [
["A",genInspectionId(),"s"],["B",d?serial(d):"","n"],["C",d?weekNo(d):"","n"],["D",d?yyyymm(d):"","s"],
["F",pkg?Number(pkg):"","n"],["G",cl,"s"],["H",cl&&pkg?"OK":"","s"],["I",$("#contractor").value||info.contractor||"","s"],
["J",info.pd||"","s"],["K",info.pm||"","s"],["L",info.cm||"","s"],["M",info.hsem||"","s"],["N",info.se||"","s"],
["O",$("#yourName").value,"s"],["P",$("#yourRole").value||"KEO","s"],["Q",$("#areaText").value,"s"],["R",$("#workersObserved")?$("#workersObserved").value:"","n"],["S",$("#mainActivity").value,"s"],["T",$("#stopWork").value,"s"],
["U",sc.Work_at_Height,"n"],["V",sc.Edge_Protection,"n"],["W",sc.Falling_Object_Prevention,"n"],["X",sc.Excavation_Safety,"n"],["Y",sc.Scaffolding_Compliance,"n"],["Z",sc.PTW_Implementation,"n"],["AA",sc.PTW_Field_Verification,"n"],["AB",sc.MSRA_Quality,"n"],["AC",sc["Lifting/Precast Installation"],"n"],["AD",sc.Traffic_Interface,"n"],["AE",sc["Housekeeping/Waste Management"],"n"],["AF",sc["Welfare Arrangement"],"n"],["AG",sc.Fire_Readiness,"n"],["AH",sc.Supervision_Subcontractor,"n"],["AI",sc.Electrical_Tool_Safety,"n"],
["AJ",st.count?st.total:"","n"],["AK",st.count?st.raw:"","n"],["AL",st.count?st.weighted:"","n"],["AM",st.count?(st.red?"YES":"NO"):"","s"],["AN",st.count?(!st.red&&st.weighted>=.9?"YES":"NO"):"","s"],["AO",$("#ratingBand").value||st.band,"s"],
["AP",$("#repeatIssue").value,"s"],["AQ",$("#rootCause").value,"s"],["AR",$("#topGaps").value,"s"],["AS",$("#immediateAction").value,"s"],["AT",$("#preventiveAction").value,"s"],["AU",$("#positiveObservations").value,"s"],["AV",$("#actionOwner").value,"s"],["AW",$("#targetCloseoutDate").value?serial($("#targetCloseoutDate").value):"","n"],["AX",$("#evidence").value,"s"],
["AY",lows,"s"],["AZ",lows,"s"],["BA",lows,"s"],["BB",lows,"s"],["BC",lows,"s"],["BD",st.count?($("#ratingBand").value||st.band):"","s"],["BE",$("#stopWork").value==="YES"?"YES":"NO","s"],["BF",st.count&&st.weighted>=.9?"YES":"NO","s"],["BG",st.count&&st.weighted<.6?"YES":"NO","s"]]}
function cellStyleId(cell){const m=String(cell||"").match(/\ss="(\d+)"/);return m?Number(m[1]):0}
function templateStylesFromRow(row){const out={};if(!row)return out;for(const m of row.xml.matchAll(/<c r="([A-Z]+)\d+"([^>]*)>/g)){const sm=String(m[2]||"").match(/\ss="(\d+)"/);if(sm)out[m[1]]=Number(sm[1])}return out}
function ensureCenterWrapBlueStyle(files,oldId){const key=String(oldId||0);if(files.styleCache[key]!==undefined)return files.styleCache[key];let styles=files.styles||"";const m=styles.match(/<cellXfs[^>]*count="(\d+)"[^>]*>([\s\S]*?)<\/cellXfs>/);if(!m){files.styleCache[key]=oldId||0;return oldId||0}const all=[...m[2].matchAll(/<xf[^>]*(?:\/>|>[\s\S]*?<\/xf>)/g)].map(x=>x[0]);let base=all[oldId]||all[0]||'<xf numFmtId="0" fontId="13" fillId="0" borderId="0" xfId="0"/>';base=base.replace(/\sfontId="\d+"/,' fontId="13"');if(!/\sfontId=/.test(base))base=base.replace('<xf','<xf fontId="13"');base=base.replace(/\sapplyFont="\d+"/,'').replace(/\sapplyAlignment="\d+"/,'').replace(/<alignment[^>]*\/>/g,'').replace(/<alignment[\s\S]*?<\/alignment>/g,'');let xf;if(/\/>\s*$/.test(base)){xf=base.replace(/\/>\s*$/, ' applyFont="1" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf>')}else{xf=base.replace(/<\/xf>\s*$/, '<alignment horizontal="center" vertical="center" wrapText="1"/></xf>').replace('<xf','<xf applyFont="1" applyAlignment="1"')}const newId=all.length;styles=styles.replace(/<cellXfs([^>]*)count="\d+"([^>]*)>/,'<cellXfs$1count="'+(newId+1)+'"$2>').replace('</cellXfs>',xf+'</cellXfs>');files.styles=styles;files.styleCache[key]=newId;return newId}
async function updateExcel(){try{setStatus("Opening original xlsx directly...");const zip=await loadZip();const workbook=await getText(zip,"xl/workbook.xml");const rels=await getText(zip,"xl/_rels/workbook.xml.rels");const sheetPath=findWeeklySheetPath(workbook,rels);let sheet=await getText(zip,sheetPath);let shared=await getText(zip,"xl/sharedStrings.xml");let styles=await getText(zip,"xl/styles.xml");const rows=getRows(sheet);const row=firstEmptyDataRow(rows);const template=rows.slice().reverse().find(x=>x.r<row.r&&x.r>=4&&hasValue(x,"B"));const files={shared,styles,styleCache:{},templateStyles:templateStylesFromRow(template)};dataMap().forEach(([col,val,type])=>setCell(row,col,val,type,files));sheet=sheet.slice(0,row.start)+row.xml+sheet.slice(row.end);zip.file(sheetPath,sheet);zip.file("xl/sharedStrings.xml",files.shared);zip.file("xl/styles.xml",files.styles);const blob=await zip.generateAsync({type:"blob",compression:"DEFLATE"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`Saadiyat_Lagoons_HSE_Weekly_Cluster_KPI_Gap_Analysis_UPDATED_ROW_${row.r}.xlsx`;a.click();setStatus(`Done. Filled existing empty original row ${row.r}. Original workbook package/design was not rebuilt. Filled cells keep original background, Calibri blue font, wrap text, horizontal center and vertical center alignment. All website data has been written.`,"success")}catch(e){console.error(e);setStatus("Failed: "+e.message,"error")}}
document.addEventListener("DOMContentLoaded",()=>{renderKpis();$("#imageInput").onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=ev=>{$("#preview").src=ev.target.result;$("#preview").style.display="block";$("#ph").style.display="none";setTimeout(readImage,200)};r.readAsDataURL(f)};$("#excelInput").onchange=e=>{excelFile=e.target.files?.[0]||null;setExcel(excelFile?`Selected original file: ${excelFile.name}`:"Included original.xlsx ready.",excelFile?"success":"")};$("#readBtn").onclick=readImage;$("#updateBtn").onclick=updateExcel;$("#inspectionDate").onchange=()=>{updateDerived();calc(true)};$("#cluster").oninput=()=>{updateDerived();calc(true)};$("#package").oninput=()=>{const p=$("#package").value.trim();if(p==="3")$("#contractor").value="INNOVO";if(p==="2"||p==="4")$("#contractor").value="TAJV";calc(true)};["mainActivity","rootCause","topGaps","immediateAction","preventiveAction","positiveObservations","actionOwner","targetCloseoutDate","evidence","repeatIssue","stopWork","yourName","yourRole","areaText"].forEach(id=>{const el=$("#"+id);if(el)el.oninput=()=>calc(false)});updateDerived()});
